-- ============================================================
-- Prototipo de base de datos V5.2
-- Proyecto: Automatización de Granja Avícola
-- Motor: PostgreSQL
-- Estado: Versión estable del prototipo
--
-- Cambios principales respecto a V5.1:
--   - tarea usa accion_inicio y accion_fin.
--   - se crea horario_tarea.
--   - se reemplaza tarea_dispositivo por horario_tarea_dispositivo.
--   - cada horario puede tener su propio grupo de dispositivos.
--   - historial_tarea depende de horario_tarea_dispositivo.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. ROLES DEL SISTEMA
-- Controlan privilegios globales de la plataforma.
-- Ejemplos: SUPERADMIN, SOPORTE, CLIENTE.
-- ============================================================

CREATE TABLE rol_sistema (
    rol_sistema_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. USUARIOS
-- Cada usuario tiene un rol global del sistema.
-- ============================================================

CREATE TABLE usuario (
    usuario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_sistema_id INTEGER NOT NULL,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(150),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_usuario_rol_sistema FOREIGN KEY (rol_sistema_id) REFERENCES rol_sistema (rol_sistema_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_usuario_username_vigente ON usuario (username)
WHERE
    eliminado_at IS NULL;

CREATE UNIQUE INDEX uq_usuario_email_vigente ON usuario (email)
WHERE
    email IS NOT NULL
    AND eliminado_at IS NULL;

-- ============================================================
-- 3. PERSONAS
-- Relación 1 a 1 con usuario.
-- ============================================================

CREATE TABLE persona (
    persona_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(30),
    documento_identidad VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_persona_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ============================================================
-- 4. GRANJAS
-- ============================================================

CREATE TABLE granja (
    granja_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ubicacion TEXT,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 5. ROLES DE GRANJA
-- Cada granja puede tener sus propios roles.
-- Ejemplos: ADMIN_GRANJA, ENCARGADO_AIRE, ENCARGADO_REPORTES.
-- ============================================================

CREATE TABLE rol_granja (
    rol_granja_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    granja_id INTEGER NOT NULL,
    nombre VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_rol_granja_granja FOREIGN KEY (granja_id) REFERENCES granja (granja_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_rol_granja_nombre_vigente ON rol_granja (granja_id, nombre)
WHERE
    eliminado_at IS NULL;

-- ============================================================
-- 6. PERMISOS
-- Catálogo global de acciones disponibles en el sistema.
-- ============================================================

CREATE TABLE permiso (
    permiso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 7. ROL_GRANJA_PERMISO
-- Relación N a N entre roles de granja y permisos.
-- ============================================================

CREATE TABLE rol_granja_permiso (
    rol_granja_permiso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_granja_id INTEGER NOT NULL,
    es_propietario BOOLEAN NOT NULL DEFAULT FALSE,
    permiso_id INTEGER NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_rol_granja_permiso_rol FOREIGN KEY (rol_granja_id) REFERENCES rol_granja (rol_granja_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_rol_granja_permiso_permiso FOREIGN KEY (permiso_id) REFERENCES permiso (permiso_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_rol_granja_permiso_vigente ON rol_granja_permiso (rol_granja_id, permiso_id)
WHERE
    eliminado_at IS NULL;

-- ============================================================
-- 8. USUARIO_GRANJA
-- Relación N a N entre usuarios y granjas.
-- El rol se asigna por granja.
-- ============================================================

CREATE TABLE usuario_granja (
    usuario_granja_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    granja_id INTEGER NOT NULL,
    rol_granja_id INTEGER NOT NULL,
    es_propietario BOOLEAN NOT NULL DEFAULT FALSE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_usuario_granja_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_granja_granja FOREIGN KEY (granja_id) REFERENCES granja (granja_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_granja_rol FOREIGN KEY (rol_granja_id) REFERENCES rol_granja (rol_granja_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_usuario_granja_vigente ON usuario_granja (usuario_id, granja_id)
WHERE
    eliminado_at IS NULL;

-- ============================================================
-- 9. TIPOS DE ÁREA
-- ============================================================

CREATE TABLE tipo_area (
    tipo_area_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 10. ÁREAS
-- ============================================================

CREATE TABLE area(
    area_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    granja_id INTEGER NOT NULL,
    tipo_area_id INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_area_granja FOREIGN KEY (granja_id) REFERENCES granja (granja_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_area_tipo FOREIGN KEY (tipo_area_id) REFERENCES tipo_area (tipo_area_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_area_nombre_por_granja UNIQUE (granja_id, nombre)
);

-- ============================================================
-- 11. TIPOS DE DISPOSITIVO
-- ============================================================

CREATE TABLE tipo_dispositivo (
    tipo_dispositivo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 12. DISPOSITIVOS
-- ============================================================

CREATE TABLE dispositivo (
    dispositivo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id INTEGER NOT NULL,
    tipo_dispositivo_id INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    device_key VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    mac_wifi VARCHAR(17) UNIQUE,
    mac_bluetooth VARCHAR(17) UNIQUE,
    ip_wifi INET,
    firmware_version VARCHAR(30),
    ultima_comunicacion TIMESTAMPTZ,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_dispositivo_area FOREIGN KEY (area_id) REFERENCES area(area_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_dispositivo_tipo FOREIGN KEY (tipo_dispositivo_id) REFERENCES tipo_dispositivo (tipo_dispositivo_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_dispositivo_mac_wifi CHECK (
        mac_wifi IS NULL
        OR mac_wifi ~* '^([0-9A-F]{2}:){5}[0-9A-F]{2}$'
    ),
    CONSTRAINT ck_dispositivo_mac_bluetooth CHECK (
        mac_bluetooth IS NULL
        OR mac_bluetooth ~* '^([0-9A-F]{2}:){5}[0-9A-F]{2}$'
    )
);

-- ============================================================
-- 13. TAREAS
--
-- accion_inicio se ejecuta al llegar hora_inicio.
-- accion_fin se ejecuta al llegar hora_fin.
--
-- Para una tarea puntual:
--   accion_fin = NULL
--   y sus horarios deben tener hora_fin = NULL.
-- ============================================================

CREATE TABLE tarea (
    tarea_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id INTEGER NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    accion_inicio VARCHAR(80) NOT NULL,
    accion_fin VARCHAR(80),
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_tarea_area FOREIGN KEY (area_id) REFERENCES area(area_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_tarea_nombre_por_area UNIQUE (area_id, nombre)
);

-- ============================================================
-- 14. HORARIO_TAREA
--
-- Cada rango horario es un registro.
-- Ejemplo:
--   Mañana: 08:00 - 08:10
--   Tarde:  16:00 - 16:10
-- ============================================================

CREATE TABLE horario_tarea (
    horario_tarea_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarea_id INTEGER NOT NULL,
    nombre VARCHAR(100),
    hora_inicio TIME NOT NULL,
    hora_fin TIME,
    dias_semana SMALLINT[] NOT NULL DEFAULT ARRAY[1, 2, 3, 4, 5, 6, 7]::SMALLINT[],
    ultima_ejecucion TIMESTAMPTZ,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_horario_tarea_tarea FOREIGN KEY (tarea_id) REFERENCES tarea (tarea_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_horario_tarea_dias CHECK (
        cardinality(dias_semana) > 0
        AND dias_semana <@ ARRAY[1, 2, 3, 4, 5, 6, 7]::SMALLINT[]
    ),
    CONSTRAINT uq_horario_tarea_programacion UNIQUE (tarea_id, hora_inicio)
);

-- ============================================================
-- 15. HORARIO_TAREA_DISPOSITIVO
--
-- Indica qué dispositivos participan en cada horario concreto.
-- ============================================================

CREATE TABLE horario_tarea_dispositivo (
    horario_tarea_dispositivo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horario_tarea_id INTEGER NOT NULL,
    dispositivo_id INTEGER NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_horario_dispositivo_horario FOREIGN KEY (horario_tarea_id) REFERENCES horario_tarea (horario_tarea_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_horario_dispositivo_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (dispositivo_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_horario_tarea_dispositivo_vigente ON horario_tarea_dispositivo (
    horario_tarea_id,
    dispositivo_id
)
WHERE
    eliminado_at IS NULL;

-- ============================================================
-- 16. HISTORIAL_TAREA
--
-- Se crea un registro por dispositivo cuando inicia un horario.
-- Se completa fecha_finalizacion cuando se ejecuta accion_fin.
-- ============================================================

CREATE TABLE historial_tarea (
    historial_tarea_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horario_tarea_dispositivo_id INTEGER NOT NULL,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_finalizacion TIMESTAMPTZ,
    estado VARCHAR(40) NOT NULL DEFAULT 'INICIADA',
    resultado JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_historial_horario_dispositivo FOREIGN KEY (horario_tarea_dispositivo_id) REFERENCES horario_tarea_dispositivo (horario_tarea_dispositivo_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_historial_tarea_estado CHECK (
        estado IN (
            'INICIADA',
            'FINALIZADA',
            'ERROR_INICIO',
            'ERROR_FINALIZACION',
            'CANCELADA'
        )
    ),
    CONSTRAINT ck_historial_tarea_fechas CHECK (
        fecha_finalizacion IS NULL
        OR fecha_finalizacion >= fecha_inicio
    )
);

CREATE UNIQUE INDEX uq_historial_tarea_abierto ON historial_tarea (horario_tarea_dispositivo_id)
WHERE
    fecha_finalizacion IS NULL
    AND estado = 'INICIADA';

-- ============================================================
-- 22. DATOS_RECIBIDOS
-- ============================================================

CREATE TABLE datos_recibidos (
    datos_recibidos_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id INTEGER NOT NULL,
    sensor VARCHAR(100),
    variable VARCHAR(100) NOT NULL,
    valor_numerico NUMERIC(18, 6),
    valor_texto TEXT,
    unidad VARCHAR(30),
    firmware_version VARCHAR(30),
    dato_original TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_datos_recibidos_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (dispositivo_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_datos_recibidos_valor CHECK (
        valor_numerico IS NOT NULL
        OR valor_texto IS NOT NULL
    )
);

-- ============================================================
-- 22. RESUMEN_SENSOR_MENSUAL
-- ============================================================

CREATE TABLE resumen_sensor_mensual (
    resumen_sensor_mensual_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id INTEGER NOT NULL,
    sensor VARCHAR(100),
    variable VARCHAR(100) NOT NULL,
    unidad VARCHAR(30),
    periodo_inicio DATE NOT NULL,
    cantidad_lecturas BIGINT NOT NULL,
    suma_valores NUMERIC(24, 6) NOT NULL,
    valor_promedio NUMERIC(18, 6) NOT NULL,
    valor_minimo NUMERIC(18, 6),
    valor_maximo NUMERIC(18, 6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_resumen_mensual_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (dispositivo_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_resumen_sensor_mensual UNIQUE (
        dispositivo_id,
        sensor,
        variable,
        periodo_inicio
    ),
    CONSTRAINT ck_resumen_cantidad_lecturas CHECK (cantidad_lecturas > 0),
    CONSTRAINT ck_resumen_periodo_inicio CHECK (
        periodo_inicio = DATE_TRUNC('month', periodo_inicio)::DATE
    )
);

-- ============================================================
-- 22. FUNCIONES
-- ============================================================

CREATE OR REPLACE FUNCTION actualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION actualizar_ultima_comunicacion()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE dispositivo
    SET ultima_comunicacion = NEW.created_at
    WHERE dispositivo_id = NEW.dispositivo_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 22. TRIGGERS
-- ============================================================

CREATE TRIGGER trg_rol_sistema_updated_at
BEFORE UPDATE ON rol_sistema
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_usuario_updated_at
BEFORE UPDATE ON usuario
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_persona_updated_at
BEFORE UPDATE ON persona
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_granja_updated_at
BEFORE UPDATE ON granja
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_rol_granja_updated_at
BEFORE UPDATE ON rol_granja
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_permiso_updated_at
BEFORE UPDATE ON permiso
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_rol_granja_permiso_updated_at
BEFORE UPDATE ON rol_granja_permiso
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_usuario_granja_updated_at
BEFORE UPDATE ON usuario_granja
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_tipo_area_updated_at
BEFORE UPDATE ON tipo_area
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_area_updated_at
BEFORE UPDATE ON area
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_tipo_dispositivo_updated_at
BEFORE UPDATE ON tipo_dispositivo
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_dispositivo_updated_at
BEFORE UPDATE ON dispositivo
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_tarea_updated_at
BEFORE UPDATE ON tarea
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_horario_tarea_updated_at
BEFORE UPDATE ON horario_tarea
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_horario_tarea_dispositivo_updated_at
BEFORE UPDATE ON horario_tarea_dispositivo
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_resumen_sensor_mensual_updated_at
BEFORE UPDATE ON resumen_sensor_mensual
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_datos_recibidos_ultima_comunicacion
AFTER INSERT ON datos_recibidos
FOR EACH ROW EXECUTE FUNCTION actualizar_ultima_comunicacion();

-- ============================================================
-- 22. ÍNDICES
-- ============================================================

CREATE INDEX idx_usuario_rol_sistema_id ON usuario (rol_sistema_id);

CREATE INDEX idx_rol_granja_granja_id ON rol_granja (granja_id);

CREATE INDEX idx_rol_granja_permiso_rol_id ON rol_granja_permiso (rol_granja_id);

CREATE INDEX idx_rol_granja_permiso_permiso_id ON rol_granja_permiso (permiso_id);

CREATE INDEX idx_usuario_granja_usuario_id ON usuario_granja (usuario_id);

CREATE INDEX idx_usuario_granja_granja_id ON usuario_granja (granja_id);

CREATE INDEX idx_usuario_granja_rol_granja_id ON usuario_granja (rol_granja_id);

CREATE INDEX idx_area_granja_id ON area(granja_id);

CREATE INDEX idx_area_tipo_area_id ON area(tipo_area_id);

CREATE INDEX idx_dispositivo_area_id ON dispositivo (area_id);

CREATE INDEX idx_dispositivo_tipo_dispositivo_id ON dispositivo (tipo_dispositivo_id);

CREATE INDEX idx_dispositivo_ultima_comunicacion ON dispositivo (ultima_comunicacion);

CREATE INDEX idx_tarea_area_id ON tarea (area_id);

CREATE INDEX idx_horario_tarea_tarea_id ON horario_tarea (tarea_id);

CREATE INDEX idx_horario_tarea_hora_inicio ON horario_tarea (hora_inicio)
WHERE
    estado = TRUE
    AND eliminado_at IS NULL;

CREATE INDEX idx_horario_tarea_hora_fin ON horario_tarea (hora_fin)
WHERE
    estado = TRUE
    AND eliminado_at IS NULL
    AND hora_fin IS NOT NULL;

CREATE INDEX idx_horario_dispositivo_horario_id ON horario_tarea_dispositivo (horario_tarea_id);

CREATE INDEX idx_horario_dispositivo_dispositivo_id ON horario_tarea_dispositivo (dispositivo_id);

CREATE INDEX idx_historial_horario_dispositivo ON historial_tarea (horario_tarea_dispositivo_id);

CREATE INDEX idx_historial_tarea_estado ON historial_tarea (estado);

CREATE INDEX idx_historial_tarea_fecha_inicio ON historial_tarea (fecha_inicio DESC);

CREATE INDEX idx_datos_recibidos_dispositivo_fecha ON datos_recibidos (
    dispositivo_id,
    created_at DESC
);

CREATE INDEX idx_datos_recibidos_variable_fecha ON datos_recibidos (variable, created_at DESC);

CREATE INDEX idx_resumen_mensual_dispositivo_periodo ON resumen_sensor_mensual (
    dispositivo_id,
    periodo_inicio DESC
);

-- ============================================================
-- 22. DATOS INICIALES
-- ============================================================

INSERT INTO
    rol_sistema (nombre, descripcion)
VALUES (
        'SUPERADMIN',
        'Administración completa de la plataforma'
    ),
    (
        'SOPORTE',
        'Soporte técnico global de la plataforma'
    ),
    (
        'CLIENTE',
        'Usuario perteneciente a una o más granjas'
    );

INSERT INTO
    permiso (codigo, nombre, descripcion)
VALUES (
        'USUARIO_CREAR',
        'Crear usuarios',
        'Permite crear usuarios dentro de una granja'
    ),
    (
        'USUARIO_EDITAR',
        'Editar usuarios',
        'Permite editar usuarios asociados a una granja'
    ),
    (
        'ROL_CREAR',
        'Crear roles',
        'Permite crear roles personalizados para una granja'
    ),
    (
        'ROL_EDITAR',
        'Editar roles',
        'Permite editar roles y sus permisos'
    ),
    (
        'DISPOSITIVO_VER',
        'Ver dispositivos',
        'Permite consultar dispositivos'
    ),
    (
        'DISPOSITIVO_EDITAR',
        'Editar dispositivos',
        'Permite registrar o modificar dispositivos'
    ),
    (
        'TAREA_VER',
        'Ver tareas',
        'Permite consultar tareas programadas'
    ),
    (
        'TAREA_CREAR',
        'Crear tareas',
        'Permite crear y programar tareas'
    ),
    (
        'TAREA_EDITAR',
        'Editar tareas',
        'Permite modificar tareas programadas'
    ),
    (
        'REPORTE_VER',
        'Ver reportes',
        'Permite consultar reportes'
    ),
    (
        'REPORTE_EXPORTAR',
        'Exportar reportes',
        'Permite exportar reportes'
    );

INSERT INTO
    tipo_area (nombre, descripcion)
VALUES (
        'GALPON',
        'Área destinada a la crianza de aves'
    ),
    (
        'ALMACEN',
        'Área para almacenamiento'
    ),
    (
        'OFICINA',
        'Área administrativa'
    ),
    (
        'SALA_TECNICA',
        'Área de equipos eléctricos y de control'
    );

INSERT INTO
    tipo_dispositivo (nombre, descripcion)
VALUES (
        'ESP32',
        'Microcontrolador ESP32'
    ),
    (
        'RASPBERRY_PI',
        'Computadora de placa única Raspberry Pi'
    ),
    (
        'GATEWAY_RS485',
        'Equipo de enlace para una red RS485'
    ),
    (
        'PLC',
        'Controlador lógico programable'
    ),
    (
        'CAMARA',
        'Dispositivo de videovigilancia o análisis'
    );

COMMIT;

-- ============================================================
-- FLUJO INICIAL RECOMENDADO
-- ============================================================
--
-- 1. El script inicial crea el usuario SUPERADMIN y su persona.
-- 2. El SUPERADMIN crea una granja.
-- 3. Crea un usuario cliente con rol_sistema CLIENTE.
-- 4. Crea un rol_granja llamado ADMIN_GRANJA para esa granja.
-- 5. Asigna todos los permisos necesarios a ADMIN_GRANJA.
-- 6. Relaciona al cliente con la granja mediante usuario_granja.
-- 7. El ADMIN_GRANJA puede crear roles internos y usuarios.
-- ============================================================

-- ============================================================
-- EJEMPLO CONCEPTUAL
-- ============================================================
--
-- tarea:
--   nombre = 'Ventilación programada'
--   accion_inicio = 'TURN_ON'
--   accion_fin = 'TURN_OFF'
--
-- horario_tarea:
--   Mañana: 08:00 - 08:10
--   Tarde:  16:00 - 16:10
--
-- horario_tarea_dispositivo:
--   Mañana -> Ventilador 1, Ventilador 2
--   Tarde  -> Ventilador 2, Ventilador 3
--
-- A las 08:00 se envía TURN_ON.
-- A las 08:10 se envía TURN_OFF y se cierra el historial.
-- ============================================================